name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, dev ]
    paths:
      - 'frontend/**'
      - '_data/**'
      - '!frontend/public/products/**'
  workflow_dispatch:
    inputs:
      deploy_message:
        description: '部署说明'
        required: false
        default: '手动触发部署'

# 添加明确的权限配置
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Setup Node.js ⚙️
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      - name: Install Dependencies 📦
        run: |
          cd frontend
          npm ci
      
      - name: Create .env, Build and Prepare 🔧🏗️📋
        run: node .github/workflows/scripts/deploy.js
        env:
          PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
      
      - name: Force Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
          clean: true
          force: true
          token: ${{ secrets.GITHUB_TOKEN }}
          exclude: |
            **/.env
            **/.env.*
            **/node_modules
            **/.git
            **/.github 