name: 处理订单

on:
  issues:
    types: [opened,edited]

  issue_comment:
    types: [created,edited]

permissions:
  issues: write
  pull-requests: write
  contents: write
  actions: write

jobs:
  process-order:
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, 'Order')
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 安装依赖
        run: npm install @actions/core @actions/github node-forge ethers@5.7.2 bs58 crypto
          
      - name: 处理Issue
        id: handle_issue
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          WALLET_MNEMONIC: ${{ secrets.WALLET_MNEMONIC }}
          TG_TOKEN_API: ${{ secrets.TG_TOKEN_API }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} 
        run: node .github/workflows/scripts/order.js
        
